### ISSUE TITLE
App is broken

### ISSUE THREAD

**Issue by emibanana** [DynamicsNinja/FlowExecutionHistory#17]
[Write any error info to resolve easier]

---
```
System.IndexOutOfRangeException:
Index was outside the bounds of the array.
Flow Execution History
- System.Collections.Generic.List`1.Add(T item)
- Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRunsFromApi(Flow flow, String status, DateTimeOffset dateFrom, Boolean includeTriggerOutputs)
- Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRuns(Flow flow, String status, DateTimeOffset dateFrom, DateTimeOffset dateTo, Int32 durationThreshold, Boolean includeTriggerOutputs)
- Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.<>c__DisplayClass26_0.<GetFlowRuns>b__3(Flow f)
- System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
- System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
- System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

---
- XrmToolBox Version: 1.2023.12.68
- FlowExecutionHistory Version: 1.2024.1.4
- DB Version: 9.2.24012.218
- Deployment: Online

**Comment by emibanana** [comment]
I dont know much about the details, it happen when i open the app today, and if i select any of the avaialble flow (after connect to the power automate api), but doing any other action this will cause an error.

by meaning any action i mean: selecting or deselecting a flow, change date, etc

**Comment by DynamicsNinja** [comment]
Do you know if it worked for you before or if you just started using the tool?

I tried on my instance that needs to connect to flow API, and everything is working fine. There is probably some other issue present in your case too.

**Comment by DynamicsNinja** [comment]
After reviewing this issue, it seems that there hasn't been any new feedback or activity for some time. In light of this, I'm going to close this issue for now. If the problem resurfaces or if you have any further information to add, please feel free to reopen it or create a new issue, and I'll be happy to assist you further.

**Comment by emibanana** [comment]
Hi, this issues still keeps happening randomly, see below log:

at Fic.XTB.FlowExecutionHistory.Services.FlowClient.<>c__DisplayClass19_0.<GetFlowRunsFromCache>b__0(FlowRunsCache x)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRunsFromCache(String flowId, String status, DateTimeOffset dateFrom)
   at Fic.XTB.FlowExecutionHistory.Services.FlowClient.GetFlowRuns(Flow flow, String status, DateTimeOffset dateFrom, DateTimeOffset dateTo, Int32 durationThreshold, Boolean includeTriggerOutputs)
   at Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.<>c__DisplayClass26_0.<GetFlowRuns>b__3(Flow f)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

**Comment by emibanana** [comment]
During this error, nothing specific was set, i open the app, connect to power automate api, succeeded, and then when i select my flow, errors occured
