### ISSUE TITLE
The utility is not loading and failing with System.IO.FileNotFoundException:

### ISSUE THREAD

**Issue by mustaqueali** [DynamicsNinja/FlowExecutionHistory#29]
Since the last update, not able to load the utility and the below error is shown:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null'
   at Fic.XTB.FlowExecutionHistory.Services.ApplicationInsights.LogEvent(String eventName)
   at Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.FlowExecutionHistory_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by DynamicsNinja** [comment]
You can try to fix it by updating the XTB version, or just follow the steps from this blog post: https://jonasr.app/missing-xrmtoolbox-pluginsstore

**Comment by mustaqueali** [comment]
Thanks @DynamicsNinja  - now it is working.  Seems this issue is related to XRMtoolbox's update and not this utility.  is this a known issue of occurring with the updates ?

**Comment by mustaqueali** [comment]
the issue is resolved now.
