### ISSUE TITLE
Repeatedly getting this error when opening Flow Execution History

### ISSUE THREAD

**Issue by llay03** [DynamicsNinja/FlowExecutionHistory#34]
System.IO.FileNotFoundException: Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'XrmToolBox.PluginsStore, Version=1.2023.1.63, Culture=neutral, PublicKeyToken=null'
   at Fic.XTB.FlowExecutionHistory.Services.ApplicationInsights.LogEvent(String eventName)
   at Fic.XTB.FlowExecutionHistory.FlowExecutionHistory.FlowExecutionHistory_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DynamicsNinja** [comment]
The issue is related to the XTB itself. You can check out issue #30 to see how to resolve it.
